included:
  - Sources
  - Tests

excluded:
  - Packages
  - .build

opt_in_rules:
  - empty_count
  - force_unwrapping

disabled_rules:
  - syntactic_sugar

variable_name:
  min_length: 1

line_length: 150

reporter: "emoji"