disabled_rules: # rule identifiers to exclude from running
  - nesting
  - function_parameter_count
opt_in_rules: # some rules are only opt-in
  - control_statement
  - empty_count
  - trailing_newline
  - colon
  - comma
  - force_unwrapping
  - file_header

included: # paths to include during linting. `--path` is ignored if present.
  - Sources
  - Tests

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Packages
  - .build
  - .vscode
  - .idea
  - ci

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning

force_try:
  severity: warning # explicitly. Give warning only for force try

type_body_length:
  warning: 300 # warning
  error: 400 # error

function_body_length:
  warning: 50
  error: 80

file_length:
  warning: 500
  error: 800

large_tuple: # warn user when using 3 values in tuple, give error if there are 4
  warning: 3
  error: 4

# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 30
    error: 35
  # excluded: iPhone # excluded via string

identifier_name:
  min_length:
    error: 3
  # excluded:
  #   - id
    
reporter: "emoji"
